### ISSUE TITLE
Link to code of conduct in Readme.md is broken

### ISSUE THREAD

**Issue by jonathanloos** [harled/monocle#31]

**Comment by Rishav1707** [comment]
Shall I work on this issue? @jonathanloos

**Comment by jonathanloos** [comment]
> Shall I work on this issue? @jonathanloos 

Thanks for this! I'll take a look tonight

**Comment by Rishav1707** [comment]
> > Shall I work on this issue? @jonathanloos
> 
> Thanks for this! I'll take a look tonight

Ok @jonathanloos
